### ISSUE TITLE
Reordering and renaming site menu sections

### ISSUE THREAD

**Issue by f-rower** [alan-turing-institute/ADViCE#19]
Rename to ADViCE Reports
Knowledge Base Community Guidelines at the bottom/right at the top
Create a Resources section

**Comment by SCostardDC** [comment]
@f-rower I'm already causing issues and I am adding 'resources' under this pull request https://github.com/alan-turing-institute/ADViCE/pull/24

**Comment by f-rower** [comment]
completed
