### ISSUE TITLE
Adding the Flexibility Webinar

### ISSUE THREAD

**Issue by SteveHaben** [alan-turing-institute/ADViCE#21]
Will be adding the webinar video https://youtu.be/vMc4-JD2-lk?si=SkuuyGiZgyQ6HifQ
to the ADViCE webinar section.
To add:

- Description of the webinar
- Embed webinar
- Other resources from webinar (links to items discussed in webinar, and the slides)

**Comment by f-rower** [comment]
Hi Steve, you forgot to add the YAML metadata to the top of the webinar markdown file

---
title: "PUT YOUR TITLE HERE"
draft: false
---

**Comment by SteveHaben** [comment]
I have now added the YAML metadata and repushed, 
waiting for review
