### ISSUE TITLE
Adding summary and link for Ecosystem Map report

### ISSUE THREAD

**Issue by SCostardDC** [alan-turing-institute/ADViCE#22]
Adding a summary / intro and link to Ecosystem Map report as a placeholder under 'ADViCE reports' (https://github.com/alan-turing-institute/ADViCE/issues/19#issue-2181795865) until we are able to get the full report into Markdown which I will aim to do in April.

**Comment by SCostardDC** [comment]
Hi @f-rower , I am not sure how to remove whats currently under 'AI for Decarbonisation Ecosystem' [section](https://github.com/alan-turing-institute/ADViCE/tree/DC-Updates-Branch/content/Reports/ADViCE%20AI%20Decarbonisation%20Ecosystem) which is the details of the challenge report.  I want to be able to add the summary and a link as discussed and i want to avoid breaking other sections but trying to remove or delete things myself. Please can you advise?

**Comment by f-rower** [comment]
Hi Susie, you can change the content by navigating to the file in your branch, and clicking on the edit button:
<img width="1169" alt="image" src="https://github.com/alan-turing-institute/ADViCE/assets/29379394/6cddb34d-6112-481f-8b46-41f0784715f3">

**Comment by SCostardDC** [comment]
Thanks @f-rower this seemed too simple :-D

**Comment by SCostardDC** [comment]
Added under this PR https://github.com/alan-turing-institute/ADViCE/pull/32
